api_platform:
  title: API Recette
  version: 1.0.0
  description: Api de recette de cuisine
  show_webby: false
  defaults:
    stateless: false
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  openapi:
    contact:
      name: Matthieu
      url: https://github.com/matt042023/recette-api2/
      email: matt.lheureux@hotmail.com
