vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /Images/
      upload_destination: "%kernel.project_dir%/public/Images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
