services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv
    working_dir: /srv
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8080:8000" # Port hôte 8080 pour accéder à l'application Symfony sur le port 8000 du conteneur
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80" # Port hôte 8081 pour accéder à Nginx sur le port 80 du conteneur
    depends_on:
      - app

  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: api
    ports:
      - "3307:3306" # Port hôte 3307 pour accéder à la base MariaDB sur le port 3306 du conteneur

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80" # Port hôte 8083 pour accéder à phpMyAdmin
    environment:
      PMA_HOST: db # Le service MariaDB défini dans docker-compose.yml
      MYSQL_ROOT_PASSWORD: root # Mot de passe root de MariaDB

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8082:8025" # Port hôte 8082 pour accéder à l'interface Mailhog sur le port 8025 du conteneur
      - "1026:1025" # Port hôte 1026 pour SMTP de Mailhog sur le port 1025 du conteneur
